language: php
php:
  - 5.4
  - 5.5
  - 5.6
before_script:
  - composer install --dev --prefer-source
  - echo "extension = mongodb.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

script: ./vendor/bin/phpunit --coverage-text
